---
- name: Make the Swap inactive 
  command: swapoff -a 

- name: Remove Swap Entry from /etc/fstab. 
  lineinfile: 
    dest: /etc/fstab
    regexp: swap 
    state: absent 
- name: Install Prerequisites for K8s
  apt: name={{ item }} state=present    
  with_items: 
   - apt-transport-https
   - ca-certificates
   - curl 
   - gnupg-agent 
   - vim 
   - software-properties-common 
    