--- 
- name: Add GPG key for docker
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present 

- name: Add docker repo 
  apt_repository: 
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable
    state: present 
    filename: docker 
    mode: 0600 

- name: Install Docker Engine 
  apt: name={{ item }} state=present
  with_items: 
   - docker-ce
   - docker-ce-cli
   - containerd.io 
 
- name: 
  service: 
    name: docker 
    state: started
    enabled: yes 
